main: com.sekwah.advancedportals.AdvancedPortalsPlugin
name: AdvancedPortals
version: 0.0.16
author: sekwah41
description: An advanced portals plugin for bukkit.
commands:
    advancedportals:
        description: The main command for the advanced portals
        aliases: [portals, aportals, portal, ap]
        usage: /<command>
    destination:
        description: Can be used to access portal destinations.
        aliases: [desti]
        usage: /<command>
    awarp:
        description: Used to warp to destinations.
        usage: /<command>
permissions:
   advancedportals.*:
     description: Gives access to all commands
     children:
       advancedportals.createportal: true
       advancedportals.portal: true
       advancedportals.build: true
       advancedportals.desti.*: true
   advancedportals.createportal:
     description: Allows you to create portals
     default: op
   advancedportals.portal:
     description: Allows use of portal commands
     default: op
   advancedportals.build:
     description: Allows you to build in the portal regions
     default: op
   advancedportals.desti.*:
     description: Gives access to all desti commands
     children:
       advancedportals.desti.create: true
   advancedportals.desti.create:
     description: Allows users to create portal destinations
     default: op
