# Advanced Portals Config

# To set this file back to its default state just delete it and reload the server or restart it!



# Set to true if you want the normal axes to work normally but the ones gived with /portals selector or wand will still work though
# It can be usefull if people with permission want to use an iron axe on a survival server
UseOnlyServerMadeAxe: false

# Preferably an item and not a block but it shouldnt matter
AxeItemId: IRON_AXE

# Will be implemented so you can give yourself the portal block and build manually with it so its easier to make portals with the portal block.
CanBuildPortalBlock: true

# Defines if portals protect themselves
PortalProtection: true

# How many blocks around the portals will be protected from griefing or destruction
PortalProtectionRadius: 5

# What the default trigger block is for portals if nothing is defined.
DefaultPortalTriggerBlock: PORTAL

# This stops all water flowing inside a portal area(can be disabled if something like world edit is handelling the water flow or you dont want it active)
#    you want to 
StopWaterFlow: true

# This must be a placeable block or it will not work and may even crash
ShowSelectionBlockID: STAINED_GLASS
ShowSelectionBlockData: 14

# WarpEffect
# 0 = disabled(no particles)
# 1 = Eye of ender explode efffect(loads of portal particles)
# 2 = Explosion particles
WarpParticles: 1

# WarpSound generally suggested to keep the same as warpeffect but can usually be used for just the sound and no particle effects
# 0 = disabled(no sound)
# 1 = Enderman Warp Sound
# 2 = Explosion
WarpSound: 1

# In case you want to show the bungee attempting warp message
ShowBungeeWarpMessage: false

# This changes how long the show seletion lasts in seconds

ShowSelectionShowDuration: 10

# If a player is riding a entity, warp the entity too?(unless its a bungee portal)

WarpRiddenEntity: true

# Use the default warp messages for portals
PortalWarpMessages: true

# Use plugin name in the warp messages
UseWarpPrefix: true

# If this is true a custom prefix can be used

UseCustomPrefix: false

CustomPrefix: '[Test]'


