# Advanced Portals Config

# To set this file back to its default state just delete it and reload the server or restart it!



# Set to true if you want the normal axes to work normally but the ones gived with /portals selector or wand will still work though
UseOnlyServerMadeAxe: false


ShowSelectionBlockID: WOOL
ShowSelectionBlockData: 14


# This changes how long the show seletion lasts in seconds

ShowSelectionShowDuration: 10