# Advanced Portals Config

# To set this file back to its default state just delete it and reload the server or restart it!



# Set to true if you want the normal axes to work normally but the ones gived with /portals selector or wand will still work though
# It can be usefull if people with permission want to use an iron axe on a survival server
UseOnlyServerMadeAxe: false

# Preferably an item and not a block but it shouldnt matter
AxeItemId: IRON_AXE

# This must be a placeable block or it will not work and may even crash
ShowSelectionBlockID: WOOL
ShowSelectionBlockData: 14


# This changes how long the show seletion lasts in seconds

ShowSelectionShowDuration: 10