main: com.sekwah.advancedportals.AdvancedPortalsPlugin
name: AdvancedPortals
version: 0.0.1
author: SEKWAH41
description: An advanced portals plugin for bukkit.
commands:
    advancedportals:
        description: The main command for the advanced portals
        aliases: [portals, aportals]
        usage: /<command>